change File Starter

diff --git a/sa b/sa
--- a/sa
+++ b/sa
@@ -142,24 +142,20 @@ update(){
 
 }
 
-if [ "$0" == "./sa" ];then
-	if [ "$1" == "--all" ] || [ "$1" == "-a" ];then
-		scan_all
-	elif [ "$1" == "-u" ] || [ "$1" == "--update" ];then
-		update
-		sleep 2
-		echo "All Packages Updated [ OK ]"
-	elif [ "$1" == "-h" ] || [ "$1" == "--help" ];then
-		echo "> ./sa or ./sa --all : Scan with All Tools"
-		echo "> ./sa -u or ./sa --update : Updates All Tools"
-		echo "> ./sa -h or --help : Help Page "
-	else
-		echo "Command Execution ERROR"
-		exit 1
-	fi
-
+if [ "$1" == "--all" ] || [ "$1" == "-a" ];then
+	scan_all
+elif [ "$1" == "-u" ] || [ "$1" == "--update" ];then
+	update
+	sleep 2
+	echo "All Packages Updated [ OK ]"
+elif [ "$1" == "-h" ] || [ "$1" == "--help" ];then
+	echo "> ./sa or ./sa --all : Scan with All Tools"
+	echo "> ./sa -u or ./sa --update : Updates All Tools"
+	echo "> ./sa -h or --help : Help Page "
 else
-	echo "ERROR on Command Execution"
+	echo "Command Execution ERROR"
+	exit 1
 fi
+
 
 
